agdsn/pycroft

.gitignore, .travis.yml, Dockerfile, docker-compose-travis.yml, docker-compose.bare.yml, docker-compose.yml, pycroft/helpers/user.py
=> Set up standalone Docker and Travis

legacy/cache_ldap.py, legacy/cache_legacy.py, legacy/conn.py.example, legacy/import_conf.py, legacy/import_legacy.py, legacy/ldap_model.py, legacy/tools.py, legacy/translate.py, pycroft/model/user.py, tests/fixtures/dummy/unixaccount.py, tests/model/test_user.py, vagrant/requirements.txt
The intent of this pull request is to resolve #3.
=> WIP ldap importer

web/templates/macros/forms.html, web/templates/user/_user_show_logs.html, web/templates/user/user_show.html
As a result of the refactorings in 3403eaee4d99be27bc463279583d356fc0b6caaa the now deleted javascript could no longer fulfill its purpose. As I do not think we need ajax powered user log entry creation, I have decided to simply delete it.
=> Minor user log improvements

web/blueprints/helpers/user.py, web/static/custom/js/table.js, web/static/style.css, web/templates/facilities/room_show.html, web/templates/macros/button.html, web/templates/user/_user_show_basedata.html
- hover messages for user-buttons in facility user lists (resolves #27)
- order of common-action-buttons on user pages changed, icons added (resolves #31)
- better style for common-action-buttons: romeved li-bullet + added margin
=> tooltips for user-buttons in facility lists, common-action-buttons on user pages

.gitignore, legacy/translate.py, pycroft/lib/membership.py, pycroft/lib/traffic.py, pycroft/lib/user.py, pycroft/model/facilities.py, pycroft/model/user.py, tests/fixtures/dummy/property.py, tests/fixtures/user_with_trafficgroups.py, tests/frontend/user/test_basic_actions.py, tests/lib/test_finance.py, tests/lib/test_property.py, tests/lib/test_user.py, tests/model/property_fixtures.py, web/blueprints/properties/__init__.py, web/blueprints/user/__init__.py, web/templates/user/_user_show_traffic.html
=> WIP: Credit granting && traffic group association

legacy/import_legacy.py, legacy/translate.py, legacy_gerok/import_gerok.py, pycroft/lib/user.py, pycroft/model/base.py, pycroft/model/config.py, pycroft/model/facilities.py, pycroft/model/finance.py, pycroft/model/host.py, pycroft/model/logging.py, pycroft/model/net.py, pycroft/model/port.py, pycroft/model/traffic.py, pycroft/model/user.py, tests/fixtures/dummy/host.py, tests/fixtures/dummy/port.py, tests/fixtures/dummy/traffic.py, tests/fixtures/hades_logs.py, tests/frontend/user/test_logs.py, tests/helpers/test_host.py, tests/lib/test_host.py, tests/lib/test_traffic.py, tests/lib/test_user.py, tests/model/test_host.py, web/blueprints/helpers/log.py, web/blueprints/infrastructure/__init__.py, web/blueprints/user/__init__.py, web/blueprints/user/log.py, web/templates/facilities/room_show.html, web/templates/infrastructure/switch_show.html
=> Interface cleanup

web/form/fields/custom.py
This should finally fix #94.
The IntervalField defaults now to 0s.
=> default for IntervalField

legacy_gerok/import_gerok.py
Updates the nvtool-importer according to the last model changes
=> Fixes importer for nvtool-dormitory Gerokstraße

compose/common-services.yml, ldap_sync/__main__.py, ldap_sync/action.py, ldap_sync/exporter.py, ldap_sync/record.py, legacy/import_conf.py, legacy_gerok/import_conf.py, pycroft/model/facilities.py, pycroft/model/finance.py, pycroft/model/host.py, pycroft/model/logging.py, pycroft/model/net.py, pycroft/model/port.py, pycroft/model/traffic.py, pycroft/model/user.py, tests/fixtures/ldap_sync/complex.py, tests/ldap_sync/test_ldap_sync.py, tests/ldap_sync/test_record.py
=> [LDAP] Sync whether login should be disabled

pycroft/lib/user.py, pycroft/model/traffic.py, tests/fixtures/dummy/traffic.py, tests/lib/test_traffic.py, web/blueprints/user/__init__.py, web/templates/user/_user_show_traffic.html
=> Traffic history

web/blueprints/user/forms.py, web/form/fields/custom.py, web/form/fields/validators.py, web/resources/js/advanced-search.js, web/resources/js/form.js, web/resources/js/mac-address-input.js, web/templates/user/change_mac.html, web/templates/user/user_create.html, web/templates/user/user_move_in.html, web/templates/user/user_search.html, webpack.config.babel.js
=>  Replace `inputMacMask()` with custom WTForms MacField

web/resources/js/table.js
=> Let table formatters specify sorting

.travis.yml, helpers/docker_cache.sh, helpers/install_latest_docker.sh
The failing tests are hades and ldap sync tests that also fail when executed locally.
=> Adapt travis configuration to reworked docker setup

pycroft/lib/facilities.py, tests/frontend/test_facilities.py, web/blueprints/facilities/__init__.py, web/blueprints/facilities/tables.py, web/templates/facilities/room_overcrowded.html
I added an page that lists all multi occupancies, or to be more precise, all rooms containing multiple users each of which has a host in the room.
@ibot3: You requested an "auto move out" feature based on the move in date. Could you elaborate on that?
=> 2 users1 room v2

pycroft/lib/net.py, pycroft/model/host.py, web/blueprints/helpers/table.py, web/blueprints/infrastructure/__init__.py, web/blueprints/infrastructure/tables.py
=> Display number of free IPs in subnet overview

.travis.yml, docker-compose.base.yml, docker-compose.test.yml, docker/dev/etc/apt/sources.list.d/yarnpkg.list, tests/hades_logs/test_hades_logs_integration.py, tests/table/test_bootstrap_table.py, tests/table/test_lazy_join.py, web/blueprints/facilities/__init__.py, web/blueprints/facilities/tables.py, web/blueprints/finance/tables.py, web/blueprints/helpers/lazy_join.py, web/blueprints/helpers/table.py, web/blueprints/infrastructure/__init__.py, web/blueprints/infrastructure/tables.py, web/blueprints/properties/tables.py, web/blueprints/user/tables.py
@ibot3 please check that all tables you touched/introduced in your PR still work as desired.
=> Switch to a declarative interface for table definitions

web/blueprints/user/__init__.py, web/templates/user/_user_show_basedata.html
=> Open datasheet in new tab

pycroft/helpers/date.py, pycroft/lib/finance.py, pycroft/lib/user.py, pycroft/model/user.py, requirements.dev.txt, tests/factories/config.py, tests/factories/finance.py, tests/factories/property.py, tests/helpers/test_date.py, tests/lib/test_finance.py, web/api/v0/__init__.py
Makes Pycroft ready for terminating memberships via SIPA.
=> Sipa cancel membership

pycroft/helpers/printing/__init__.py, pycroft/model/address.py, scripts/server_run.py
To send the usersheets by post this PR adds the postal address of the users to the usersheets. Therefore the usersheet has been slightly restructured.
The usersheet now looks like this:
=> Postal address on usersheet

web/blueprints/finance/__init__.py, web/resources/js/table.js
=> add support for empty transaction descriptions

pycroft/model/alembic/versions/3ec1d29bfd10_add_fints_product_id.py, pycroft/model/config.py, requirements.txt, setup.py, web/blueprints/finance/__init__.py, web/blueprints/helpers/fints.py
Added product id to initialization
=> Fix FinTS import

.gitmodules, pycroft/lib/finance.py, tests/factories/property.py, tests/lib/test_finance.py
=> Match abe transactions

pycroft/helpers/interval.py, pycroft/model/ddl.py
=> Import ABC from collections.abc explicitly.

.eslintrc.yml, package-lock.json, package.json, web/resources/js/lazy-load-select.js, web/resources/js/mac-address-input.js, web/resources/js/tooltip.js
In an attempt to understand how the LazyLoadSelect plugin works, I read up on the current best practises and ES6+ language features. This lead to some improvements.
I did:
- Refactor LazyLoadSelect to incorporate lots of ES6+ improvements
- The same with the vendor lookup
- Set up ESLint
=> JS improvements

docker/base.Dockerfile, docker/base/container/hooks/init/90_fix_celery, docker/base/etc/apt/sources.list, docker/dev/container/hooks/init/10_venv, pycroft/helpers/i18n.py, requirements.txt, tests/lib/test_finance.py, web/resources/js/hello.ts, web/resources/main.js, web/templates/user/user_show.html, webpack.config.babel.js
This PR changes the python version to 3.9 based on debian buster.
Closes #387
=> Python 3.9 - Buster

web/blueprints/facilities/tables.py, web/blueprints/infrastructure/tables.py, web/resources/js/table.js
Fixes switch and patch port sorting in tables.
Fixes #384
=> Fix port sorting

docker-compose.test.yml, tests/__init__.py
=> Ci deadlock

pycroft/templates/mail/member_request_denied.html, pycroft/templates/mail/member_request_pending.html, pycroft/templates/mail/user_confirm_email.html, pycroft/templates/mail/user_moved_in.html
Edited mail templates, e.g. hint to the new status page.
=> Edit mail templates

README.md, pycroft/lib/task.py, pycroft/lib/user.py, pycroft/task.py, web/blueprints/user/__init__.py, web/blueprints/user/forms.py, web/resources/css/style.css, web/templates/user/user_move.html
=> Comment field for relocations

.gitmodules, README.md, requirements.txt, tests/table/test_bootstrap_table.py, tests/table/test_lazy_join.py, web/blueprints/facilities/tables.py, web/blueprints/finance/__init__.py, web/blueprints/finance/tables.py, web/blueprints/helpers/log.py, web/blueprints/host/tables.py, web/blueprints/infrastructure/tables.py, web/blueprints/task/__init__.py, web/blueprints/task/tables.py, web/blueprints/user/__init__.py, web/blueprints/user/tables.py, web/table/lazy_join.py, web/table/table.py
=> Reintegrate bootstrap table py

pycroft/exc.py, pycroft/lib/exc.py, pycroft/lib/facilities.py, pycroft/lib/finance.py, pycroft/lib/infrastructure.py, pycroft/lib/mail.py, pycroft/lib/net.py, pycroft/lib/task.py, pycroft/lib/user.py, pycroft/model/finance.py, pycroft/model/host.py, pycroft/model/types.py, pycroft/model/user.py, pycroft/task.py, tests/factories/__init__.py, tests/lib/test_task.py, web/blueprints/__init__.py, web/blueprints/task/__init__.py
- Fixes #465
- Also adds a unit test for `cancel_task`
Screenshots:
=> Manual task exe

.idea/runConfigurations/_template__of_py_test.xml, .idea/runConfigurations/pytest_everything.xml, .idea/runConfigurations/pytest_lib.xml, .idea/runConfigurations/pytest_model.xml, docker-compose.base.yml, docker-compose.dev.yml, docker-compose.prod.yml, docker-compose.test.yml, pycroft/lib/finance.py, pycroft/model/alembic/versions/0e78d83dad0b_use_native_tstzrange_type_for_.py, pycroft/model/alembic/versions/20234ac06668_use_tstzrange_for_room_history_entry.py, pycroft/model/alembic/versions/6815546f681c_add_exclusion_constraint_to_membership.py, pycroft/model/alembic/versions/c11d3d8b16ae_building_fee_account.py, pycroft/model/base.py, pycroft/model/user.py, tests/factories/user.py, tests/lib/test_finance.py, tests/lib/user/test_room_history.py, tests/lib/user/test_similarity.py, web/blueprints/facilities/__init__.py, web/blueprints/user/__init__.py
=> Interval types for Room History Entry

web/api/v0/__init__.py
=> Resolve "Failed member verification (due to semicolon in last name)"

pycroft/helpers/i18n.py, pycroft/lib/infrastructure.py, pycroft/model/host.py, tests/lib/infrastructure/__init__.py, tests/lib/infrastructure/conftest.py, tests/lib/infrastructure/test_switch.py, web/blueprints/infrastructure/__init__.py
=> Fix create_switch logging

.github/workflows/docker-image.yml, requirements.dev.txt
Tries to assist in discovering #577 by publishing test reports
=> [ci] Improved test reporting

.github/workflows/docker-image.yml, pycroft/model/finance.py, tests/factories/__init__.py, tests/factories/config.py, tests/frontend/assertions.py, tests/frontend/conftest.py, tests/frontend/test_finance.py, tests/model/test_finance.py, web/blueprints/finance/__init__.py
Refs #15, #624
This adds various frontend tests to the `finance` blueprint in order to improve its coverage (from 45% to 52%).
=> Finance frontend tests, part 1

pycroft/model/logging.py, tests/factories/finance.py, tests/factories/property.py, tests/frontend/fixture_helpers.py, tests/frontend/test_finance.py, tests/frontend/test_meta.py, web/blueprints/finance/__init__.py, web/blueprints/helpers/host.py, web/blueprints/user/forms.py, web/template_filters.py, web/templates/finance/transactions_create.html
=> Finance frontend tests, part 2: Transaction/membership fee CRUD

pycroft/lib/logging.py, tests/conftest.py, tests/frontend/test_facilities.py, tests/lib/test_logging.py, web/blueprints/facilities/__init__.py, web/blueprints/facilities/forms.py
=> Frontend tests facilities

tests/factories/__init__.py, tests/frontend/test_facilities.py, web/blueprints/facilities/__init__.py
=> Remaining tests for `web.blueprints.facilities`

web/resources/css/style.css, web/templates/facilities/room_show.html
=> Minor improvements in `room_show` template

web/api/v0/__init__.py
Fixes https://github.com/agdsn/sipa/issues/472
=> Fix location of /user/from-ip GET request args

pycroft/model/alembic.ini, pycroft/model/alembic/versions/55e9f0d9b5f4_add_custom_non_blocking_radius_groups.py, pycroft/model/hades.py, tests/model/test_hades.py, web/commands.py
=> Nonblocking custom radius groups

pycroft/lib/membership.py, tests/lib/test_membership.py, web/blueprints/user/__init__.py
=> Fix Editing membership: can't adapt type 'SimpleMessage' (#512)

web/templates/user/user_show.html
fixed the typo for show user from tasks to mpsk_clients
Signed-off-by: Alex <robokatze182@gmx.de>
#744
=> fixed typo in frontend

pycroft/lib/membership.py, web/blueprints/user/__init__.py, web/blueprints/user/tables.py
=> Allow memberships beginning in the future to be deleted

web/resources/js/table.js
fixed a missing sort attribute for textWithBooleanFormatter also moved the icon displaying the state to the back in order for it to 
fixes #765
=> fixed missing sort attributet

pycroft/model/__init__.py
set transaction level to serializable in order to mitigate phantom reads / r hits which where then committed
this prevents #768 from being run multiple times
=> set higher transaction level
