pycroft/helpers/user.py

At least in Courier, which my form was printed in, those characters are almost indistinguishable

Get rid of hard to distinguish characters in password generation(e.g. l/1 0/O)

---

legacy/reconstruct_memberships.py
legacy/translate.py

Sometimes, instead of the regular membership fee, a smaller one has been
booked by the head of finance, to compensate for the smaller interval of
membership.  In most cases, this can be used to reconstruct the
membership intervals in higher precisions (instead of throwing an error
due to fee amount inconsistencies).

Reconstruct customly small membership intervals

---

server_run.py
web/app.py

app.create_jinja_environment evaluates app.debug to decide whether it
should enable template auto reloading or not. Passing the debug flag
to app.run is not helping, because at this time
app.create_jinja_environment already has been called.

Set flask debug flag early to make template reloading work

---

pycroft/lib/user.py
pycroft/model/ddl.py
pycroft/model/finance.py
pycroft/model/traffic.py
tests/factories/host.py
tests/factories/net.py
tests/factories/traffic.py
tests/factories/user.py
tests/fixtures/dummy/traffic.py
tests/model/test_ddl.py
tests/model/test_traffic.py
web/blueprints/user/__init__.py
web/templates/finance/accounts_show.html
web/templates/user/_user_show_traffic.html

Fixes #111, about to fix #122 
Left todo:

WIP: Views and rules

---

legacy/netusers_model.py

Doing the legacy import failed with
```
Traceback (most recent call last):
File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/pycroft/legacy/import_legacy.py", line 40, in <module>
from . import netusers_model
File "/pycroft/legacy/netusers_model.py", line 28, in <module>
class Nutzer(Base):
File "/pycroft/legacy/netusers_model.py", line 60, in Nutzer
computer = relationship("Computer", backref="nutzer")
NameError: name 'relationship' is not defined
```
so I imported `relationship` from `sqlalchemy.orm`

fixed importer

---

legacy/translate.py
pycroft/lib/finance.py
pycroft/model/finance.py
tests/fixtures/dummy/finance.py
tests/lib/finance_fixtures.py
vagrant/requirements.txt
web/blueprints/finance/__init__.py
web/blueprints/finance/forms.py
web/templates/finance/bank_accounts_import.html

Bank account transactions can now be imported via FinTS. The credentials for logging into the bank account are not saved anywhere (except the FinTS-URI).
Before importing all potentially new transactions, they're checked if they are new transactions. Potentially new are those transactions, which took place on the day of the last import or later.
With this PR also a bug, which occurred while listing all existing bank accounts when one of those hasn't had any transactions, was fixed.
Closes #182

Retrieve bank account transactions via FinTS

---

helpers/interactive.py
ldap_sync/exporter.py
legacy/import_legacy.py
legacy_gerok/import_gerok.py
pycroft/lib/finance.py
pycroft/lib/user.py
pycroft/model/__init__.py
pycroft/model/finance.py
pycroft/model/functions.py
pycroft/model/logging.py
pycroft/model/property.py
pycroft/model/session.py
pycroft/model/traffic.py
pycroft/model/types.py
pycroft/model/user.py
pycroft/model/webstorage.py
scripts/server_run.py
tests/__init__.py
tests/lib/test_user.py
tests/model/test_property.py
tests/model/test_traffic.py

Task list taken from the corresponding issue #162:

Switch to timestamp with timezone

---

pycroft/lib/finance.py
pycroft/lib/user.py
web/blueprints/finance/__init__.py
web/blueprints/finance/forms.py
web/templates/finance/bank_accounts_list.html
web/templates/finance/bank_accounts_match.html
web/templates/finance/bank_accounts_matched.html

This is a simple and quick implementation to match unassigned bank-account activities.
The references of the unmatched BankAccountActivities are matched against:
- User-ID type 1
- User-ID type 2
- `gerok38/Name`
So most of the activities should be matched to a user.

match unassigned bank-account activities

---

hades_logs/parsing.py

Log for Users in dormitories RBS and Gutz show HTTP Error 500 because the Switches in these dormitories are not able to do radius auth. If there Is an empty answer from Hades, it causes an HTTP 500.

Fix RuntimeError on empty Radius-Logs

---

docker-compose.base.yml
docker-compose.test.yml
docker/dev/container/commands/dummy-worker
docker/dev/container/hooks/init/90_fix_celery
tests/hades_logs/__init__.py
tests/hades_logs/test_hades_logs_integration.py

Mostly reviving the celery dummy worker in our new docker setup. Additionally, I added a nasty workaround script that patches celery and its dependency kombu, to make them compatible with Python 3.7 (https://github.com/celery/celery/issues/4500). An official fix is announced for version 4.3, originally scheduled for November 30, 2018, but now rescheduled for January 31th, 2019. If we update to celery 4.3 we also have to upgrade hades to celery 4, because celery 4 is not backward compatible to celery 3.

Fix hadeslog tests

---

web/templates/user/_user_show_basedata.html

In Chromium it is hard to mark the name and birth date because it will try to move the link itself. This makes that easier. Also there is no reason for the link to contain the complete text.

Move name and birth date out of link so they are easier to copy

---

web/blueprints/finance/__init__.py
web/blueprints/finance/forms.py
web/templates/finance/bank_accounts_import.html
web/templates/finance/bank_accounts_import_manual.html

This PR adds the possibility to import transactions without the use of FinTS.
The transactions need to be downloaded from the online banking as a MT940 file which will be uploaded to Pycroft. The MT940 is saved like an unsuccessfull FinTS import. So, after uploading the file, the transactions can be reviewed and imported.

manual mt940 bank import

---

pycroft/helpers/interval.py
pycroft/lib/finance.py
pycroft/lib/user.py
pycroft/model/alembic/versions/c11d3d8b16ae_building_fee_account.py
pycroft/model/facilities.py
pycroft/model/finance.py
pycroft/model/net.py
pycroft/model/user.py
tests/__init__.py
tests/factories/config.py
tests/factories/facilities.py
tests/factories/property.py
tests/factories/user.py
tests/fixtures/dummy/facilities.py
tests/fixtures/dummy/finance.py
tests/lib/finance_fixtures.py
tests/lib/test_finance.py
tests/lib/test_user.py
web/blueprints/finance/__init__.py
web/blueprints/finance/tables.py
web/blueprints/host/forms.py
web/blueprints/user/__init__.py
web/blueprints/user/tables.py
web/templates/user/_user_show_room_history.html
web/templates/user/user_show.html

This PR adds the ability to book membership fees separated by dormitory (closes #328).
An additional room history is created for every user that keeps track in which period a user lived in a room.
If a fee is booked, it is checked in which room a user lived at the end of the fee period and at the beginning of the period as an alternative.
By default, the current fee account is used and the account of a dormitory can be changed in the database.
This PR also add test cases for fee booking and handling of overdue users. (closes #197).
I also changed the design of the user overview to a tabbed layout (closes #367).

Membership fee per dorm

---

pycroft/lib/user.py
pycroft/model/alembic/versions/27f7f8832dfa_add_pre_member_group.py
pycroft/model/alembic/versions/fb8d553a7268_add_account_pattern.py
pycroft/model/config.py
tests/factories/config.py

Add a new user to a `pre-member` group, if the move-in date is in the future.
Required, so that users that will be a member in the future are able to login on SIPA before their membership starts.

Add user to a `pre-member` group, if the move-in date is in the future

---

doc/arch/adr-001.rst
doc/arch/adr-XXX.rst
doc/conf.py
doc/index.rst
requirements.dev.txt

In my six years of contribution, I've often witnessed people having great ideas of how to structure things, which became forgotten more quickly than they became known by the devs working on the relevant code.
This is an example of how I would (sometimes) like to persist a decision I made about our internal architecture ([pre-render for the lazy](http://agdsn.me/~lukasjuhrich/pycroft/arch/adr-001.html)).
The purpose of these ADRs would not be to add bureaucracy to the way make our decisions (I think the process is fine-as-is – in particular I don't want every decision to have to be “vetted” by a PR reviewer), but simply to make any decisions that we _already make_ visible.
This causes
1. …decisions and their rationale to be as transparent in six months as they were at the time of their …

Introduce an Architecture Decision Record

---

doc/arch/adr-003.rst
doc/index.rst
pycroft/helpers/interval.py
pycroft/lib/finance.py
pycroft/lib/user_deletion.py
pycroft/model/base.py
pycroft/model/config.py
pycroft/model/property.py
pycroft/model/user.py
scripts/server_run.py
tests/model/test_user.py
web/blueprints/user/__init__.py
web/blueprints/user/tables.py
web/resources/js/table.js
web/templates/user/archivable_users.html

This is a preliminary overview for which users would be marked as `to-be-archived`.
The next step would be to
1. Implement a lib function to mark these users as `to-be-archived` and filter out `to-be-archived` users in `get_archivable_members`
2. Split up this table into three tables with the same columns: 
i. Users to-be-marked (i.e. what's returned from `get_archivable_members`)
ii. Users who are `to-be-archived`
iii. Users who are `to-be-archived` _and_ `do-not-archive` (i.e. invalidated memberships)
3. Implement a lib routine that actually archives the users, which fails if there are invalidated memberships
Refs #470

Add query for archivable users and display them in table

---

pycroft/exc.py
pycroft/lib/exc.py
pycroft/lib/facilities.py
pycroft/lib/finance.py
pycroft/lib/infrastructure.py
pycroft/lib/mail.py
pycroft/lib/net.py
pycroft/lib/task.py
pycroft/lib/user.py
pycroft/model/finance.py
pycroft/model/host.py
pycroft/model/types.py
pycroft/model/user.py
pycroft/task.py
tests/factories/__init__.py
tests/lib/test_task.py
web/blueprints/__init__.py
web/blueprints/task/__init__.py
web/blueprints/user/__init__.py
web/templates/user/user_show.html

This changes some descriptions and turns the user tabs from this:
Into this:
I'd say this is a valuable change since I found myself scanning the page for the `Aufgaben` tab way too often. having a unified description and icons definitely helps me.
Also, I've noticed how my eyes first focused on the number badges, which provide the least important information, hence I've turned `bg-secondary` into `bg-light`.

Icons + Improved naming for user tabs

---

doc/arch/adr-005.rst
doc/index.rst
web/blueprints/finance/__init__.py
web/blueprints/helpers/exception.py
web/blueprints/helpers/user.py
web/blueprints/host/__init__.py
web/blueprints/user/__init__.py

@ibot3 Can you give me some feedback on this idea?
(Also relates to #493)
As mentioned previously, the value proposal is that calling functions directly can leverage IDE autocompletion and static analysis (i.e. type hints, or even just “knowing the function signature”). A call of the form `web_execute(func, success_message, *actual_arguments)` makes this impossible and is harder to reason about.

Proposal: Replace `web_execute` by context manager and base exception

---

web/api/v0/__init__.py

Fix registration for tenants with semicolon after last name

---

package-lock.json
package.json
tests/table/test_bootstrap_table.py
web/resources/js/table.js
web/table/table.py
webpack.config.babel.js

Fix bootstrap-table build after update

---

pycroft/lib/finance/transaction_crud.py

A bank account activity is new, if *no* similar activity statement exists.

Fix logical error introduced in 165cc580bd68e6aef895019a5dc9b0764180d869

---

pyproject.toml
tests/factories/property.py
tests/frontend/test_host.py
tests/frontend/test_interface.py
web/blueprints/host/__init__.py

Host web tests

---

tests/factories/facilities.py
tests/frontend/test_host.py
tests/frontend/test_infrastructure.py
tests/model/test_hades.py
web/blueprints/helpers/exception.py
web/blueprints/infrastructure/__init__.py

Infra web tests

---

pycroft/lib/host.py
pycroft/model/host.py
requirements.txt
tests/factories/finance.py
tests/frontend/test_task.py
web/blueprints/facilities/__init__.py
web/blueprints/facilities/tables.py
web/blueprints/finance/__init__.py
web/blueprints/finance/tables.py
web/blueprints/helpers/log.py
web/blueprints/helpers/log_tables.py
web/blueprints/helpers/user.py
web/blueprints/host/__init__.py
web/blueprints/host/tables.py
web/blueprints/infrastructure/__init__.py
web/blueprints/infrastructure/tables.py
web/blueprints/properties/__init__.py
web/blueprints/task/__init__.py
web/blueprints/task/tables.py
web/blueprints/user/__init__.py
web/blueprints/user/tables.py
web/resources/js/traffic-graph.js
web/table/table.py

The goal of this PR is to replace the dicts returned in the table JSON endpoints by pydantic models.
After having done this, frontend tests can utilize these models to validate responses and do easier introspection.
possible next issue:

Pydantic models for table json responses

---

docker-compose.test.yml
pycroft/lib/user.py
web/api/v0/__init__.py

UserResource perf improvements

---

web/api/v0/__init__.py

Due to the migration to webargs, request args are no longer attributes of the `args` object but function parameters.  During the migration, `args.` have simply been stripped from the paramters without proper checking whether variables with the same name are already in use, causing a varible collision i.e. an unintended override.

[web] Fix variable collision in API

---

pycroft/lib/user.py
tests/lib/user/test_active_members.py

Group send mail bug

---

justfile

added swdd.sql schema import for database
added for this also a create view

changed justfile

---

pycroft/lib/facilities.py

to use itertools.groupby() the iterable needs to be sorted see https://docs.python.org/3/library/itertools.html#itertools.groupby

fix overcrowded view see #631

---

.github/workflows/docker-image.yml
.pre-commit-config.yaml
docker/base.Dockerfile
docker/dev.Dockerfile
docker/dev/container/hooks/init/10_venv
ldap_sync/concepts/record.py
pycroft/helpers/i18n/message.py
pycroft/helpers/interval.py
pycroft/lib/finance/matching.py
pycroft/lib/task.py
pycroft/lib/user.py
pycroft/lib/user_deletion.py
pycroft/model/alembic/versions/ff700db83195_add_address_relation.py
pycroft/model/base.py
pycroft/model/session.py
pycroft/model/task_serialization.py
pyproject.toml
requirements.txt
scripts/render_mypy_results.py
scripts/render_sphinx_log.py
scripts/server_run.py
web/blueprints/facilities/__init__.py
web/blueprints/facilities/forms.py
web/blueprints/user/__init__.py
web/table/lazy_join.py
web/table/table.py

This allows for the use of helpful features and typing improvements. Plus, performance

Upgrade to python 3.11

---

web/resources/js/tab-anchor.ts
web/resources/js/user-suite.ts
web/templates/user/user_show.html
webpack.config.babel.js

added a key navigation on the user suite
solves #683

added feature key navigation user suite

---

pyproject.toml
web/blueprints/finance/forms.py

Until now, the default date was the one the app was started on as the value was calculated on class initialisation.

Fix default date for transaction creation

---

tests/frontend/test_facilities.py
web/blueprints/facilities/__init__.py
web/blueprints/facilities/tables.py
web/templates/facilities/room_show.html

@hw0lff creating this PR for you so I can already leave a quick review before tomorrow.

Add tenancies to room view

---

web/blueprints/facilities/__init__.py
web/blueprints/facilities/tables.py

With this PR, the person_id is also shown in the webview, even if no user could be mapped.

Room tenancies, find lost commits

---

bundle.ts
web/resources/js/tab-anchor.ts

Apparently issues appear when bundling Bootstrap in multiple files.

Always enable splitting during bundling

---

justfile
pycroft/lib/finance/fints.py
pyproject.toml
tests/external_services/test_fints.py
web/blueprints/finance/__init__.py
web/blueprints/finance/forms.py
web/blueprints/finance/tables.py
web/templates/finance/bank_accounts_import.html
web/templates/finance/fints_login.html
web/templates/finance/fints_tan.html

Fix fints login

---

tests/frontend/api/test_user.py
web/api/v0/__init__.py

until now the mpsk clients would not been send when loading a user via the API

fixed sending mpsk clients when loading user data

---

web/blueprints/finance/__init__.py
web/templates/finance/fints_tan.html

Bank import: After input online banking username & pin, a tan challenge start. Pycroft show a qr code, which we have to scan with our tan device. It response firstly with the startcode of this transaction. To check, if challenge started correctly, pycroft now can show the startcode too.

Show startcode at fints tan challenge

---

web/resources/js/table.js

there was a typo in the which did not add the attriubte to relativeDateFormatter 
#764

Typo in table js  removed

---

tests/frontend/api/test_mpsk.py
web/api/v0/__init__.py

Fixes that now users can not add or create mpsk clients
fixed #772

Bug fix/mpsk not member

---

tests/frontend/user/test_basic_actions.py
web/blueprints/user/__init__.py

Currently, when you click on the 'End membership' button on a group (intended or accidentally), the group membership is ended without any confirmation, leading to possible unwanted situations.
This PR implements a simple confirmation form before performing the actual ending operation.

confirm group membership ending
